name: todo_justdoit
description: Todo app from scratch

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.0
  sqflite: ^1.3.1
  path: ^1.6.4
  simple_gesture_detector: ^0.1.5
  flutter_launcher_icons: ^0.8.1
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/assets/logo-big.jpg"

flutter:
  uses-material-design: true
  assets:
    - images/assets/add.jpeg
    - images/assets/
    - images/assets/logo.png

